services:
  mongodb:
    image: mongo:latest
    container_name: ranksterr-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Changed to use named volume
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:

